tourpay/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myapp.user.urls")),
    path('', include("myapp.pay.urls")),
    path('', include("myapp.tour.urls")),
    path('', include("myapp.package.urls")),
    path('', include("myapp.purchase.urls")),
]

tourpay/myapp/pay/urls.py
from django.urls import path
from . import views

app_name = "pay"

urlpatterns = [    
path("pay/", views.payIndex.as_view(), name="결제"), 
path("pay/add", views.payAdd.as_view(), name="결제수단등록"), 
path("pay/list", views.payList.as_view(), name="결제수단목록"), 
]

tourpay/myapp/tour/urls.py
from django.urls import path
from . import views

app_name = "tour"

urlpatterns = [    
path("tour/", views.tourIndex.as_view(), name="행사"), 
path("tour/add-qr", views.tourAddqr.as_view(), name="행사추가"),
path("tour/add-code", views.tourAddcode.as_view(), name="행사추가"),
path("tour/check", views.tourCheck.as_view(), name="행사추가"),
path("tour/sc-check", views.scheduleCheck.as_view(), name="행사추가"),
]

tourpay/myapp/user/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views


app_name = "user"

urlpatterns = [    
    path("index/", views.userIndex.as_view(), name="main"), 
    path('login/', views.login, name='login'),
    path('signup/', views.signup.as_view(), name='signup'),
    path("", views.firstIndex.as_view(), name="first_index"), 
    ]

tourpay/myapp/package/models.py
from django.db import models

# Create your models here.

tourpay/myapp/pay/models.py
from django.db import models

# Create your models here.

tourpay/myapp/purchase/models.py
from django.db import models

# Create your models here.

tourpay/myapp/tour/models.py
from django.db import models

# Create your models here.

tourpay/myapp/user/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import User


class LoginForm(forms.Form):
    userId = forms.CharField(label='휴대전화번호')
    userPassword = forms.CharField(widget=forms.PasswordInput, label='비밀번호')

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='password1', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('contact_no', 'name')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('contact_no', 'password',
                  'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]
    

tourpay/myapp/package/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import update_session_auth_hash
from django.contrib import auth, messages
from django.urls import reverse_lazy
# Create your views here.

class packageIndex(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "package/index.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)
    

class packageList(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "package/list.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)
    

class packageOption(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "package/option.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)
    
class packagePayment(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "package/payment.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)
    

tourpay/myapp/pay/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import update_session_auth_hash
from django.contrib import auth, messages
from django.urls import reverse_lazy
# Create your views here.

class payIndex(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "pay/index.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)

class payAdd(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "pay/add.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)

class payList(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "pay/list.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)

tourpay/myapp/purchase/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import update_session_auth_hash
from django.contrib import auth, messages
from django.urls import reverse_lazy
# Create your views here.

class purchaseIndex(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "purchase/index.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)
    
class purchaseDetail(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "purchase/detail.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)

class purchaseCancel(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "purchase/cancel.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)

tourpay/myapp/tour/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import update_session_auth_hash
from django.contrib import auth, messages
from django.urls import reverse_lazy
# Create your views here.

class tourIndex(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "tour/index.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)
    

class tourList(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "tour/list.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)
    

class tourAddqr(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "tour/add-qr.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)
    
class tourAddcode(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "tour/add-code.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)
    

class tourCheck(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "tour/tour-check.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)
    

class scheduleCheck(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "tour/schedule-check.html"

    def get(self, request, *args, **kwargs):        
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                       
                        "dataList":""}

        return render(request, self.template_name, self.content)
    

tourpay/myapp/user/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import update_session_auth_hash
from django.contrib import auth, messages
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from .forms import UserCreationForm
# Create your views here.


class userIndex(generic.ListView):
    def __init__(self):
        self.title_nm = "메인페이지입니다."
        self.ogImgUrl = ""
        self.descript = "메인페이지입니다."
        self.template_name = "user/index.html"

    def get(self, request, *args, **kwargs):
        self.content = {"descript": self.descript,
                        "title_nm": self.title_nm,
                        "ogImgUrl": self.ogImgUrl,
                        "dataList": "[[[[ Hellow DJango ]]]]"}

        return render(request, self.template_name, self.content)


class signup(generic.ListView):
    def __init__(self):
        self.title_nm = "회원가입"
        self.ogImgUrl = ""
        self.descript = "회원가입"
        self.template_name = "user/signup.html"

    def get(self, request, *args, **kwargs):
        self.content = {"descript": self.descript,
                        "title_nm": self.title_nm,
                        "ogImgUrl": self.ogImgUrl,
                        "dataList": ""}

        return render(request, self.template_name, self.content)


def login(request):
    error = None

    if request.method == "POST":
        username = request.POST.get('userId')
        password = request.POST.get('userPassword')

        if username and password:
            if not username.isdigit():
                error = '핸드폰 번호는 숫자로만 입력해야 합니다.'
            else:
                user = auth.authenticate(request, username=username, password=password)

                if user is not None:
                    auth.login(request, user)
                    return redirect('/pay/')
                else:
                    error = '아이디와 패스워드가 일치하지 않습니다.'
        else:
            error = '핸드폰 번호를 입력해주세요.'

    return render(request, 'user/login.html', {'error': error})


def logout(request):
    auth.logout(request)
    return redirect('/user/login.html')



def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()  # 사용자 생성
            return redirect('/pay/')  # 회원가입 성공 시 리다이렉트할 URL
    else:
        form = UserCreationForm()

    return render(request, 'user/signup.html', {'form': form})

    
class firstIndex(generic.ListView):
    def __init__(self):
        self.title_nm       = ""
        self.ogImgUrl       = ""
        self.descript       = ""
        self.template_name  = "index.html"

    def get(self, request, *args, **kwargs):
        self.content = {"descript":self.descript,
                        "title_nm":self.title_nm,
                        "ogImgUrl":self.ogImgUrl,                                               
                        "dataList":""}

        return render(request, self.template_name, self.content)
    

tourpay/myapp/templates/user/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

tourpay/myapp/templates/user/index.html
{{dataList}}

tourpay/myapp/templates/user/login.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>TOUR PAY</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>


<body>
    <div class="container container-tourpay pb-6">
        <div class="row">
            <p style="text-align: center; margin-top: 100px;">
                <img src="/static/assets/img/logo.svg">
            </p>
        </div>
        <div class="row" style="text-align: center; margin-top: 100px;">
            <form method="post" action="{% url 'user:login' %}" id="login-from">
                {% csrf_token %}
                <div class="md-3"></div>
                <div class="input-group">
                    <div class="user d-flex align-items-center justify-content-center">
                        <img src="/static/assets/img/ico-member.svg">
                        <input type="text" name="userId" id="userId" class="form__input icon_id" placeholder="휴대전화번호">
                    </div>
                </div>
                <div class="input-group">
                    <div class="password">
                        <img src="/static/assets/img/ico-password.svg">
                        <input type="password" name="userPassword" id="userPassword" class="form__input"
                            placeholder="비밀번호">
                    </div>
                </div>
                <div class="mt-5"></div>
                <input type="submit" value="로그인" class="submit-btn">
                <input type="button" value="회원가입" class="signup-btn" onclick="document.location.href='../signup'">
                {% if error %}
                <p style="font-size: 14px; font-weight: bold; color: red; text-align: center;">{{ error }}</p>
                {% endif %}
            </form>
        </div>
</body>
{% if user.is_authenticated %}
<!--로그인상태일때 실행할부분-->
{%else%}
<!--비로그인시 실행할부분-->
{%endif%}




<style>
    .pt-4 {
        padding-top: 24px !important;
    }

    .pt-5 {
        padding-top: 40px !important;
    }

    .pb-6 {
        padding-bottom: 4rem !important;
    }

    .submit-btn {
        color: aliceblue;
        font-size: 16px;
        background-color: #2b8eff;
        margin: 30px 10px 0px 0px;
        padding: 10px;
        opacity: 1;
        border: none;
        border-radius: 6px;
        top: 459px;
        left: 16px;
        width: 100%;
        height: 52px;
    }

    .signup-btn {
        color: #2b8eff;
        font-size: 16px;
        background-color: #ffffff;
        margin: 5px 10px 10px 0px;
        opacity: 1;
        border-color: #2b8eff;
        border-width: 1px;
        border-radius: 6px;
        left: 16px;
        width: 100%;
        height: 52px;
    }

    .user {
        position: relative;
        width: 100%;
        text-align: center;

    }

    .user img {
        position: absolute;
        width: 25px;
        top: 12px;
        left: 3px;
        margin: 0;
    }

    .password {
        position: relative;
        width: 100%;
        text-align: center;

    }

    .password img {
        position: absolute;
        width: 25px;
        top: 12px;
        left: 3px;
        margin: 0;
    }

    input::placeholder {
        text-indent: 20px;
        color: #c3c4c6
    }


    .form__input {
        width: 100%;
        border: 0px solid transparent;
        border-radius: 0;
        border-bottom: 1px solid #e1e3e6;
        padding: 1em .5em .5em;
        padding-left: 2em;
        outline: none;
        margin: .5em auto;
        transition: all .5s ease;
    }

    .form__input:focus {
        border-bottom-color: #2b8eff;
        box-shadow: 0 0 5px rgba(0, 80, 80, .4);
        border-radius: 4px;
    }
</style>

tourpay/myapp/templates/user/registration.html
<!-- registration.html -->
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입">
</form>

tourpay/myapp/templates/user/signup.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>TOUR PAY</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>


<body>
    <div class="container">
        <div class="row">
            <div class="container-main">
                <div class="main-title">회원가입</div>
            </div>
        </div>
        <div class="row" style="border-bottom: #f5f7f9 solid 1px;"></div>
    </div>
    <div class="container container-tourpay pb-6" style="background-color: #f5f7f9;">
        <div class="row mt-3" style="background-color: #ffffff;">
                <div class="container container-sm">
                    <div class="row mt-3">
                        <p style="text-align: left;">
                            <img src="/static/assets/img/logo.svg" style="height: 21px;">
                        <p style="margin: -15px 0px 30px 0px; color: #888888;">투어페이 이용을 위해선 회원가입이 필요합니다.</p>
                    </div>
                    <div class="md-3"></div>
                    <div class="mb-2">
                        <label for="name" class="form-label">이름</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="이름을 입력해주세요">
                    </div>
                    <div class="mt-3"></div>
                    <div class="mb-2">
                        <label for="contact_no" class="form-label">휴대전화번호</label>
                        <input type="number" class="form-control" id="contact_no" name="contact_no" placeholder="휴대전화번호를 입력해주세요">
                    </div>
                    <div class="mt-3"></div>
                    <div class="mb-2">
                        <label for="password" class="form-label">비밀번호</label>
                        <input type="password" class="form-control" id="password2" name="password1" placeholder="비밀번호를 입력해주세요">
                    </div>
                    <div class="mt-3"></div>
                    <div class="mb-2">
                        <label for="password_check" class="form-label">비밀번호 확인</label>
                        <input type="password" class="form-control" id="password2" name="password2"   placeholder="비밀번호를 한번 더 입력해주세요">
                    </div>
                    <div class="mt-3"></div>
                    <div class="mb-2">
                        <label for="birth_date" class="form-label">생년월일</label>
                        <input type="number" class="form-control" id="date_of_birth" name="date_of_birth" placeholder="생년월일 8자리를 입력해주세요">
                    </div>
                    <div class="mt-5"></div>
                    <div class="card">
                        <div class="card-header">
                            <div class="form-check" style="padding: 1px 0px 0px 0px;">
                                <input class="from-check-input" type="checkbox" value="" id="total_agreement">
                                <label class="form-check-label" for="total_agreement">전체동의</label>
                            </div>
                        </div>
                        <div class="form-check" style="padding: 5px 0px 5px 20px;">
                            <input class="from-check-input" type="checkbox" value="" id="total_agreement">
                            <label class="form-check-label" for="total_agreement">이용약관 동의(필수)</label>
                        </div>
                        <div class="form-check" style="padding: 2px 0px 5px 20px;">
                            <input class="from-check-input" type="checkbox" value="" id="total_agreement">
                            <label class="form-check-label" for="total_agreement">개인정보 취급방침 동의(필수)</label>
                        </div>
                        <div class="form-check" style="padding: 2px 0px 5px 20px;">
                            <input class="from-check-input" type="checkbox" value="" id="total_agreement">
                            <label class="form-check-label" for="total_agreement">이용약관 동의(선택)</label>
                        </div>
                    </div>

                    <input type="submit" value="회원가입" class="submit-btn" onclick="document.location.href='../pay'">
                    <input type="button" value="취소" class="cancel-btn" onclick="document.location.href='../login'">
                </div>
            </form>
        </div>
    </div>
</body>


<style>
    input::placeholder {
        text-indent: 20px;
        color: #c3c4c6
    }

    .form-control {
        width: 100%;
        height: 48px;
        border: 0px solid transparent;
        border-radius: 6px;
        border: 1px solid #e1e3e6;
        padding: 1em;
        padding-left: 1em;
        outline: none;
    }

    .form__input {
        width: 100%;
        border: 0px solid transparent;
        border-radius: 0;
        border-bottom: 1px solid #e1e3e6;
        padding: 1em .5em .5em;
        padding-left: 2em;
        outline: none;
        margin: .5em auto;
        transition: all .5s ease;
    }

    .form__input:focus {
        border-bottom-color: #2b8eff;
        box-shadow: 0 0 5px rgba(0, 80, 80, .4);
        border-radius: 4px;
    }
</style>